name = "moe-counter"
main = "dist/worker.js"
compatibility_date = "2024-02-27"
workers_dev = false

[[routes]]
pattern = "moe-counter.fwan9678.workers.dev"
custom_domain = true

[build]
command = "npm run build"

[[d1_databases]]
binding = "DB"
database_name = "moe-counter"
database_id = "8ba3d2ae-c7ae-4a09-9621-bc1ffe67b3d4"
